<#
.SYNOPSIS
    This file helps create and execute tests for UDE.
    
    Copyright © 2024 Microsoft. All rights reserved.
#>

[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"
Trace-VstsEnteringInvocation $MyInvocation
try
{
    #get the testsuite files based on the built dlls
    Write-Host "Fetching test suites to run"
    $xppBinPath = Get-VstsInput -Name "XppBinariesPath" -Require
    $xppBinSearch = Get-VstsInput -Name "XppBinariesSearch" -Default "*"
    if ($xppBinSearch.Contains("`n"))
    {
        [string[]]$xppBinSearch = $xppBinSearch -split "`n"
    }
    Assert-VstsPath -LiteralPath $xppBinPath -PathType Container
    $potentialPackages = Find-VstsMatch -DefaultRoot $xppBinPath -Pattern $xppBinSearch | Where-Object { (Test-Path -LiteralPath $_ -PathType Container) }
    #$potentialPackages = @("C:\AOSService\PackagesLocalDirectory\AAAAUTest1")
    
    if ($potentialPackages.Length -gt 0)
    {
        $compilerPath = Get-VstsInput -Name "CompilerPath" -Require
        $platformPath = Get-VstsInput -Name "PlatformPath" -Require
        Assert-VstsPath -LiteralPath $compilerPath -PathType Container
        Assert-VstsPath -LiteralPath $platformPath -PathType Container
        $refPaths = Get-VstsInput -Name "ReferencePaths"
        $platformPath = Join-Path -Path $platformPath -ChildPath "ref"
        $platformPath = Join-Path -Path $platformPath -ChildPath "net40"
        Assert-VstsPath -LiteralPath $platformPath -PathType Container
        Import-Module "$PSScriptRoot\TestRequestTSXFetch.ps1" -Force
        $testSuiteDirectory = Get-TestTSXDirectory -potentialPackages $potentialPackages -compilerPathInput $compilerPath -platformPathInput $platformPath -referencePaths $refPaths

        #get connection info from params to create a CRMServiceClient object
        $cloudPackagePlatVersion = Get-VstsInput -Name "CloudPackagePlatVersion" -Require
        $cloudPackageAppVersion = Get-VstsInput -Name "CloudPackageAppVersion" -Require
        $regexVersion = '^\d+\.\d+\.\d+\.\d+$'
        if ($cloudPackagePlatVersion -notmatch $regexVersion) 
        {
            throw "Invalid platform version: $cloudPackagePlatVersion"
        }
        if ($cloudPackageAppVersion -notmatch $regexVersion) 
        {
            throw "Invalid application version: $cloudPackageAppVersion"
        }
        
        $connString = Get-VstsInput -Name 'PowerPlatformEnvironment' -Require
        #call the unit test operation assume there is svcCLone object and tsx file
        Write-Host "Creating cloud runtime unittest request"
        $PSVersionTable
        Import-Module "$PSScriptRoot\CloudRuntimeUnitTestRequest.ps1" -Force
        Create-CloudRuntimeUnitTestRequest -connectionString "$connString" -platVersionNumber "$cloudPackagePlatVersion" -appVersionNumber "$cloudPackageAppVersion" -testSuiteDirectory "$testSuiteDirectory"
    }
    else
    {
        throw "No matching potential packages found."        
    }
}
finally
{
    Trace-VstsLeavingInvocation $MyInvocation
}

# SIG # Begin signature block
# MIIoJwYJKoZIhvcNAQcCoIIoGDCCKBQCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCAKQ0OO2tbu2wdn
# JPqT3pFx35QBOtm+msnPLbMV8Mbro6CCDXYwggX0MIID3KADAgECAhMzAAAEBGx0
# Bv9XKydyAAAAAAQEMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjQwOTEyMjAxMTE0WhcNMjUwOTExMjAxMTE0WjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQC0KDfaY50MDqsEGdlIzDHBd6CqIMRQWW9Af1LHDDTuFjfDsvna0nEuDSYJmNyz
# NB10jpbg0lhvkT1AzfX2TLITSXwS8D+mBzGCWMM/wTpciWBV/pbjSazbzoKvRrNo
# DV/u9omOM2Eawyo5JJJdNkM2d8qzkQ0bRuRd4HarmGunSouyb9NY7egWN5E5lUc3
# a2AROzAdHdYpObpCOdeAY2P5XqtJkk79aROpzw16wCjdSn8qMzCBzR7rvH2WVkvF
# HLIxZQET1yhPb6lRmpgBQNnzidHV2Ocxjc8wNiIDzgbDkmlx54QPfw7RwQi8p1fy
# 4byhBrTjv568x8NGv3gwb0RbAgMBAAGjggFzMIIBbzAfBgNVHSUEGDAWBgorBgEE
# AYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQU8huhNbETDU+ZWllL4DNMPCijEU4w
# RQYDVR0RBD4wPKQ6MDgxHjAcBgNVBAsTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEW
# MBQGA1UEBRMNMjMwMDEyKzUwMjkyMzAfBgNVHSMEGDAWgBRIbmTlUAXTgqoXNzci
# tW2oynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20vcGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3JsMGEG
# CCsGAQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDovL3d3dy5taWNyb3NvZnQu
# Y29tL3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3J0
# MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIBAIjmD9IpQVvfB1QehvpC
# Ge7QeTQkKQ7j3bmDMjwSqFL4ri6ae9IFTdpywn5smmtSIyKYDn3/nHtaEn0X1NBj
# L5oP0BjAy1sqxD+uy35B+V8wv5GrxhMDJP8l2QjLtH/UglSTIhLqyt8bUAqVfyfp
# h4COMRvwwjTvChtCnUXXACuCXYHWalOoc0OU2oGN+mPJIJJxaNQc1sjBsMbGIWv3
# cmgSHkCEmrMv7yaidpePt6V+yPMik+eXw3IfZ5eNOiNgL1rZzgSJfTnvUqiaEQ0X
# dG1HbkDv9fv6CTq6m4Ty3IzLiwGSXYxRIXTxT4TYs5VxHy2uFjFXWVSL0J2ARTYL
# E4Oyl1wXDF1PX4bxg1yDMfKPHcE1Ijic5lx1KdK1SkaEJdto4hd++05J9Bf9TAmi
# u6EK6C9Oe5vRadroJCK26uCUI4zIjL/qG7mswW+qT0CW0gnR9JHkXCWNbo8ccMk1
# sJatmRoSAifbgzaYbUz8+lv+IXy5GFuAmLnNbGjacB3IMGpa+lbFgih57/fIhamq
# 5VhxgaEmn/UjWyr+cPiAFWuTVIpfsOjbEAww75wURNM1Imp9NJKye1O24EspEHmb
# DmqCUcq7NqkOKIG4PVm3hDDED/WQpzJDkvu4FrIbvyTGVU01vKsg4UfcdiZ0fQ+/
# V0hf8yrtq9CkB8iIuk5bBxuPMIIHejCCBWKgAwIBAgIKYQ6Q0gAAAAAAAzANBgkq
# hkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
# EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
# bjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5
# IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEwOTA5WjB+MQswCQYDVQQG
# EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwG
# A1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQg
# Q29kZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC
# CgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+laUKq4BjgaBEm6f8MMHt03
# a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc6Whe0t+bU7IKLMOv2akr
# rnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4Ddato88tt8zpcoRb0Rrrg
# OGSsbmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+lD3v++MrWhAfTVYoonpy
# 4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nkkDstrjNYxbc+/jLTswM9
# sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6A4aN91/w0FK/jJSHvMAh
# dCVfGCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmdX4jiJV3TIUs+UsS1Vz8k
# A/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL5zmhD+kjSbwYuER8ReTB
# w3J64HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zdsGbiwZeBe+3W7UvnSSmn
# Eyimp31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3T8HhhUSJxAlMxdSlQy90
# lfdu+HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS4NaIjAsCAwEAAaOCAe0w
# ggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRIbmTlUAXTgqoXNzcitW2o
# ynUClTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYD
# VR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBDuRQFTuHqp8cx0SOJNDBa
# BgNVHR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2Ny
# bC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3JsMF4GCCsG
# AQUFBwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
# L3BraS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3J0MIGfBgNV
# HSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEFBQcCARYzaHR0cDovL3d3
# dy5taWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1hcnljcHMuaHRtMEAGCCsG
# AQUFBwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkAYwB5AF8AcwB0AGEAdABl
# AG0AZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn8oalmOBUeRou09h0ZyKb
# C5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7v0epo/Np22O/IjWll11l
# hJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0bpdS1HXeUOeLpZMlEPXh6
# I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/KmtYSWMfCWluWpiW5IP0
# wI/zRive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvyCInWH8MyGOLwxS3OW560
# STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBpmLJZiWhub6e3dMNABQam
# ASooPoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJihsMdYzaXht/a8/jyFqGa
# J+HNpZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYbBL7fQccOKO7eZS/sl/ah
# XJbYANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbSoqKfenoi+kiVH6v7RyOA
# 9Z74v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sLgOppO6/8MO0ETI7f33Vt
# Y5E90Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtXcVZOSEXAQsmbdlsKgEhr
# /Xmfwb1tbWrJUnMTDXpQzTGCGgcwghoDAgEBMIGVMH4xCzAJBgNVBAYTAlVTMRMw
# EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
# aWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNp
# Z25pbmcgUENBIDIwMTECEzMAAAQEbHQG/1crJ3IAAAAABAQwDQYJYIZIAWUDBAIB
# BQCggZAwGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwLwYJKoZIhvcNAQkEMSIE
# IPzXRsy8SzcjI59ZciWC7+zmClYXgkMLlXYBcuoVLRstMEIGCisGAQQBgjcCAQwx
# NDAyoBSAEgBNAGkAYwByAG8AcwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29m
# dC5jb20wDQYJKoZIhvcNAQEBBQAEggEABUyLGGZZPTlIL2IInuydqAaE6bL7B2uI
# QyP0eLfRcBVG+0QUEJhxHdRgS0nMhu9QQCFY/T/fB8Y8NeJ6NiRMHP1nx90ie7d5
# 03TzhLamFUBl8YPcCRP5C7I+IbODQFmlPT9oHd27VvEnGvN1kyB7lYkumlwo17qt
# 4AYWPPmK1MP281V7A+hJGNXmcGZ3PVg0cm8+5ID9TVQSlO4yrrqU76xOFnxMnEzn
# 1oduF150q4tCxcr4BLSyqV0PTmcQDf0vTxiMXjwJHRQUaSEGG9sC+FAYqVx/4hSY
# IXIhdlaRcO+74idgDSuAHHrn+9APJ7aMO97os4z590VTxWMhIJD1g6GCF68wgher
# BgorBgEEAYI3AwMBMYIXmzCCF5cGCSqGSIb3DQEHAqCCF4gwgheEAgEDMQ8wDQYJ
# YIZIAWUDBAIBBQAwggFZBgsqhkiG9w0BCRABBKCCAUgEggFEMIIBQAIBAQYKKwYB
# BAGEWQoDATAxMA0GCWCGSAFlAwQCAQUABCAtYdvMcVMU+QeFHSEOMxDMwORrn3gY
# Pl43Ocwbp57x/gIGZ+0t1rlfGBIyMDI1MDQxODAwMjAxOC40MlowBIACAfSggdmk
# gdYwgdMxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
# EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xLTArBgNV
# BAsTJE1pY3Jvc29mdCBJcmVsYW5kIE9wZXJhdGlvbnMgTGltaXRlZDEnMCUGA1UE
# CxMeblNoaWVsZCBUU1MgRVNOOjJBMUEtMDVFMC1EOTQ3MSUwIwYDVQQDExxNaWNy
# b3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNloIIR/jCCBygwggUQoAMCAQICEzMAAAH5
# H2eNdauk8bEAAQAAAfkwDQYJKoZIhvcNAQELBQAwfDELMAkGA1UEBhMCVVMxEzAR
# BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1p
# Y3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3Rh
# bXAgUENBIDIwMTAwHhcNMjQwNzI1MTgzMTA5WhcNMjUxMDIyMTgzMTA5WjCB0zEL
# MAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1v
# bmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEtMCsGA1UECxMkTWlj
# cm9zb2Z0IElyZWxhbmQgT3BlcmF0aW9ucyBMaW1pdGVkMScwJQYDVQQLEx5uU2hp
# ZWxkIFRTUyBFU046MkExQS0wNUUwLUQ5NDcxJTAjBgNVBAMTHE1pY3Jvc29mdCBU
# aW1lLVN0YW1wIFNlcnZpY2UwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoIC
# AQC0PUwffIAdYc1WyUL4IFOP8yl3nksM+1CuE3tZ6oWFF4L3EpdKOhtbVkfMdTxX
# YE4lSJiDt8MnYDEZUbKi9S2AZmDb4Zq4UqTdmOOwtKyp6FgixRCuBf6v9UBNpbz8
# 41bLqU7IZnBmnF9XYRfioCHqZvaFp0C691tGXVArW18GVHd914IFAb7JvP0kVnjk
# s3amzw1zXGvjU3xCLcpUkthfSJsRsCSSxHhtuzMLO9j691KuNbIoCNHpiBiFoFoP
# ETYoMnaxBEUUX96ALEqCiB0XdUgmgIT9a7L0y4SDKl5rUd6LuUUa90tBkfkmjZBH
# m43yGIxzxnjtFEm4hYI57IgnVidGKKJulRnvb7Cm/wtOi/TIfoLkdH8Pz4BPi+q0
# /nshNewP0M86hvy2O2x589xAl5tQ2KrJ/JMvmPn8n7Z34Y8JxcRih5Zn6euxlJ+t
# 3kMczii8KYPeWJ+BifOM6vLiCFBP9y+Z0fAWvrIkamFb8cbwZB35wHjDvAak6EdU
# lvLjiQZUrwzNj2zfYPLVMecmDynvLWwQbP8DXLzhm3qAiwhNhpxweEEqnhw5U2t+
# hFVTHYb/ROvsOTd+kJTy77miWo8/AqBmznuOX6U6tFWxfUBgSYCfILIaupEDOkZf
# KTUe80gGlI025MFCTsUG+75imLoDtLZXZOPqXNhZUG+4YQIDAQABo4IBSTCCAUUw
# HQYDVR0OBBYEFInto7qclckj16KPNLlCRHZGWeAAMB8GA1UdIwQYMBaAFJ+nFV0A
# XmJdg/Tl0mWnG1M1GelyMF8GA1UdHwRYMFYwVKBSoFCGTmh0dHA6Ly93d3cubWlj
# cm9zb2Z0LmNvbS9wa2lvcHMvY3JsL01pY3Jvc29mdCUyMFRpbWUtU3RhbXAlMjBQ
# Q0ElMjAyMDEwKDEpLmNybDBsBggrBgEFBQcBAQRgMF4wXAYIKwYBBQUHMAKGUGh0
# dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY2VydHMvTWljcm9zb2Z0JTIw
# VGltZS1TdGFtcCUyMFBDQSUyMDIwMTAoMSkuY3J0MAwGA1UdEwEB/wQCMAAwFgYD
# VR0lAQH/BAwwCgYIKwYBBQUHAwgwDgYDVR0PAQH/BAQDAgeAMA0GCSqGSIb3DQEB
# CwUAA4ICAQBmIAmAVuR/uN+HH+aZmWcZmulp74canFbGzwjv29RvwZCi7nQzWezu
# LAbYJx2hdqrtWClWQ1/W68iGsZikoIFdD5JonY7QG/C4lHtSyBNoo3SP/J/d+kcP
# SS0f4SQS4Zez0MEvK3vWK61WTCjD2JCZKTiggrxLwCs0alI7N6671N0mMGOxqya4
# n7arlOOauAQrI97dMCkCKjxx3D9vVwECaO0ju2k1hXk/JEjcrU2G4OB8SPmTKcYX
# +6LM/U24dLEX9XWSz/a0ISiuKJwziTU8lNMDRMKM1uSmYFywAyXFPMGdayqcEK31
# 35R31VrcjD0GzhxyuSAGMu2De9gZhqvrXmh9i1T526n4u5TR3bAEMQbWeFJYdo76
# 7bLpKLcBo0g23+k4wpTqXgBbS4NZQff04cfcSoUe1OyxldoM6O3JGBuowaaR/woj
# eohUFknZdCmeES5FuH4CCmZGf9rjXQOTtW0+Da4LjbZYsLwfwhWT8V6iJJLi8Wh2
# GdwV60nRkrfrDEBrcWI+AF5tFbJW1nvreoMPPENvSYHocv0cR9Ns37igcKRlrUcq
# XwHSzxGIUEx/9bv47sQ9n7AwfzB2SNntJux1211GBEBGpHwgU9a6tD6yft+0SJ9q
# iPO4IRqFIByrzrKPBB5M831gb1vfhFO6ueSkP7A8ZMHVZxwymwuUzTCCB3EwggVZ
# oAMCAQICEzMAAAAVxedrngKbSZkAAAAAABUwDQYJKoZIhvcNAQELBQAwgYgxCzAJ
# BgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25k
# MR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jv
# c29mdCBSb290IENlcnRpZmljYXRlIEF1dGhvcml0eSAyMDEwMB4XDTIxMDkzMDE4
# MjIyNVoXDTMwMDkzMDE4MzIyNVowfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldh
# c2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBD
# b3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIw
# MTAwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDk4aZM57RyIQt5osvX
# JHm9DtWC0/3unAcH0qlsTnXIyjVX9gF/bErg4r25PhdgM/9cT8dm95VTcVrifkpa
# /rg2Z4VGIwy1jRPPdzLAEBjoYH1qUoNEt6aORmsHFPPFdvWGUNzBRMhxXFExN6AK
# OG6N7dcP2CZTfDlhAnrEqv1yaa8dq6z2Nr41JmTamDu6GnszrYBbfowQHJ1S/rbo
# YiXcag/PXfT+jlPP1uyFVk3v3byNpOORj7I5LFGc6XBpDco2LXCOMcg1KL3jtIck
# w+DJj361VI/c+gVVmG1oO5pGve2krnopN6zL64NF50ZuyjLVwIYwXE8s4mKyzbni
# jYjklqwBSru+cakXW2dg3viSkR4dPf0gz3N9QZpGdc3EXzTdEonW/aUgfX782Z5F
# 37ZyL9t9X4C626p+Nuw2TPYrbqgSUei/BQOj0XOmTTd0lBw0gg/wEPK3Rxjtp+iZ
# fD9M269ewvPV2HM9Q07BMzlMjgK8QmguEOqEUUbi0b1qGFphAXPKZ6Je1yh2AuIz
# GHLXpyDwwvoSCtdjbwzJNmSLW6CmgyFdXzB0kZSU2LlQ+QuJYfM2BjUYhEfb3BvR
# /bLUHMVr9lxSUV0S2yW6r1AFemzFER1y7435UsSFF5PAPBXbGjfHCBUYP3irRbb1
# Hode2o+eFnJpxq57t7c+auIurQIDAQABo4IB3TCCAdkwEgYJKwYBBAGCNxUBBAUC
# AwEAATAjBgkrBgEEAYI3FQIEFgQUKqdS/mTEmr6CkTxGNSnPEP8vBO4wHQYDVR0O
# BBYEFJ+nFV0AXmJdg/Tl0mWnG1M1GelyMFwGA1UdIARVMFMwUQYMKwYBBAGCN0yD
# fQEBMEEwPwYIKwYBBQUHAgEWM2h0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lv
# cHMvRG9jcy9SZXBvc2l0b3J5Lmh0bTATBgNVHSUEDDAKBggrBgEFBQcDCDAZBgkr
# BgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUw
# AwEB/zAfBgNVHSMEGDAWgBTV9lbLj+iiXGJo0T2UkFvXzpoYxDBWBgNVHR8ETzBN
# MEugSaBHhkVodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2NybC9wcm9kdWN0
# cy9NaWNSb29DZXJBdXRfMjAxMC0wNi0yMy5jcmwwWgYIKwYBBQUHAQEETjBMMEoG
# CCsGAQUFBzAChj5odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpL2NlcnRzL01p
# Y1Jvb0NlckF1dF8yMDEwLTA2LTIzLmNydDANBgkqhkiG9w0BAQsFAAOCAgEAnVV9
# /Cqt4SwfZwExJFvhnnJL/Klv6lwUtj5OR2R4sQaTlz0xM7U518JxNj/aZGx80HU5
# bbsPMeTCj/ts0aGUGCLu6WZnOlNN3Zi6th542DYunKmCVgADsAW+iehp4LoJ7nvf
# am++Kctu2D9IdQHZGN5tggz1bSNU5HhTdSRXud2f8449xvNo32X2pFaq95W2KFUn
# 0CS9QKC/GbYSEhFdPSfgQJY4rPf5KYnDvBewVIVCs/wMnosZiefwC2qBwoEZQhlS
# dYo2wh3DYXMuLGt7bj8sCXgU6ZGyqVvfSaN0DLzskYDSPeZKPmY7T7uG+jIa2Zb0
# j/aRAfbOxnT99kxybxCrdTDFNLB62FD+CljdQDzHVG2dY3RILLFORy3BFARxv2T5
# JL5zbcqOCb2zAVdJVGTZc9d/HltEAY5aGZFrDZ+kKNxnGSgkujhLmm77IVRrakUR
# R6nxt67I6IleT53S0Ex2tVdUCbFpAUR+fKFhbHP+CrvsQWY9af3LwUFJfn6Tvsv4
# O+S3Fb+0zj6lMVGEvL8CwYKiexcdFYmNcP7ntdAoGokLjzbaukz5m/8K6TT4JDVn
# K+ANuOaMmdbhIurwJ0I9JZTmdHRbatGePu1+oDEzfbzL6Xu/OHBE0ZDxyKs6ijoI
# Yn/ZcGNTTY3ugm2lBRDBcQZqELQdVTNYs6FwZvKhggNZMIICQQIBATCCAQGhgdmk
# gdYwgdMxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
# EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xLTArBgNV
# BAsTJE1pY3Jvc29mdCBJcmVsYW5kIE9wZXJhdGlvbnMgTGltaXRlZDEnMCUGA1UE
# CxMeblNoaWVsZCBUU1MgRVNOOjJBMUEtMDVFMC1EOTQ3MSUwIwYDVQQDExxNaWNy
# b3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNloiMKAQEwBwYFKw4DAhoDFQCqzlaNY7vN
# UAqYhx3CGqBm/KnpRqCBgzCBgKR+MHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpX
# YXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQg
# Q29ycG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAy
# MDEwMA0GCSqGSIb3DQEBCwUAAgUA66txyzAiGA8yMDI1MDQxNzEyMjU0N1oYDzIw
# MjUwNDE4MTIyNTQ3WjB3MD0GCisGAQQBhFkKBAExLzAtMAoCBQDrq3HLAgEAMAoC
# AQACAggFAgH/MAcCAQACAhKDMAoCBQDrrMNLAgEAMDYGCisGAQQBhFkKBAIxKDAm
# MAwGCisGAQQBhFkKAwKgCjAIAgEAAgMHoSChCjAIAgEAAgMBhqAwDQYJKoZIhvcN
# AQELBQADggEBADYhovEviFD/AsIwpAIZsE3YY+9pBmp5xnFAFgWnmz0RoHHNGTRn
# NNzl6V7X7l3j0YfGlNiRzcAqW4xTE2mWBCadOnFinxPlu4vig84LL/D6hPtAMkV+
# Uqh1wcGRxehYS178lFl9jYqAlYAb4VjVVqdpeBoMBAc0gtXPrE79gAL6nqd9BsRW
# rjaRCDN0NCeMFNlkb29KeSYY9j0YvqasGMnY7KB/eVB22m7u2/vcQifiG1eUsVZD
# SiLt+fmoa1/Na7CU05THVikaJBsYzdhz2B2jtFUwJqK9PL/7ieTh0UsPOXldqbco
# G9v5nD5UmXma2Xeqnjipl+0IxqdkTW8sK1oxggQNMIIECQIBATCBkzB8MQswCQYD
# VQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEe
# MBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNyb3Nv
# ZnQgVGltZS1TdGFtcCBQQ0EgMjAxMAITMwAAAfkfZ411q6TxsQABAAAB+TANBglg
# hkgBZQMEAgEFAKCCAUowGgYJKoZIhvcNAQkDMQ0GCyqGSIb3DQEJEAEEMC8GCSqG
# SIb3DQEJBDEiBCAO9VUeJbMw/cFHLUcq40ZoGvu099IUiBT4oyyvcLaigjCB+gYL
# KoZIhvcNAQkQAi8xgeowgecwgeQwgb0EIDkjjMge8I37ZPrpFQ4sJmtQRV2gqUqX
# xV4I7lJsYtgQMIGYMIGApH4wfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hp
# bmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jw
# b3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTAC
# EzMAAAH5H2eNdauk8bEAAQAAAfkwIgQg5F6BNMcnpKSNwYOJYt85KeNfql6HxII8
# 9Qn5Zh2GINgwDQYJKoZIhvcNAQELBQAEggIAeE7Cs32JG5LDpRqO2b7ZamcArc+M
# xLkAefr0cFvaTMiJlo6DJ4lCsAysCiKff9t2Sn1N+Ne2wEWSKBrKPaViyTgV1aw8
# qjC5owYAqF3musImw1yqor4sSLa8E+sjOvM+Th2exzUg2iZHVOuw48oE/M3ceJCs
# bM/PJMY/Pqgdo0YnGrKreZ0yyP6bjOT1agsZtYEQv+xyODiKhDWLayVr7Q5/Mp/L
# azOBmjUpHY3YPEjpra35B7arqC0Zibs3xyJ/C8ZgSGdDAWfOl0cK7km/oKJK0Rbn
# HVePkczQ86am86h7wHd5nRzFw70Nxg57yA3+RQ37fHCEeWCLiDn/w3pbNTLKr2yC
# zQn785fKtCDpBd3BRNWSEnWDhF/wdumKkVni5pfjJmLy/hwkBllY5cbekLJbpZ9i
# OdEGcypcxheOqhcyXrvI/KTXlI7dANLxwBA6x2b1N2XoSiGearynu4EvIsmvIxYR
# laI75EKYDq2mXZ21HnaG9oDJ2bDh3d8mRtqFBvJ7ViZsVVhjG6RYcQpo1nMgCDgb
# 5yGqhUsuea2OOGLd0bl/hsk4iGqtAXCswWuqcBfCZWmNqEzZbyWmqW9cj6roLdwv
# r7rjiRPkO6O2GKDe3qBqjrtegckiyr+N4NdQWqN94Bo0tANjhE35W1nVG+BCkjDs
# UY3Hjcv23chdG8A=
# SIG # End signature block
